export const MOODS = [
  {
    label: 'Hip-Hop / Rap',
    genreId: 'hip_hop',
    c1: '#5856d6',
    c2: '#2d2c8e',
    img: 'assets/moods/hip-hop.jpg',
  },
  {
    label: 'Pop',
    genreId: 'pop',
    c1: '#fa243c',
    c2: '#9b0a1a',
    img: 'assets/moods/pop.jpg',
  },
  {
    label: 'Rock',
    genreId: 'rock',
    c1: '#ff2d55',
    c2: '#a50020',
    img: 'assets/moods/rock.jpg',
  },
  {
    label: 'Electronic',
    genreId: 'electronic',
    c1: '#00c7be',
    c2: '#007a77',
    img: 'assets/moods/edm.jpg',
  },
  {
    label: 'Country',
    genreId: 'country',
    c1: '#ca8a04',
    c2: '#78350f',
    img: 'assets/moods/country.jpg',
  },
  {
    label: 'Jazz',
    genreId: 'jazz',
    c1: '#007aff',
    c2: '#004aad',
    img: 'assets/moods/jazz.jpg',
  },
  {
    label: 'Classical',
    genreId: 'classical',
    c1: '#64748b',
    c2: '#1e293b',
    img: 'assets/moods/classical.jpg',
  },
  {
    label: 'Latin',
    genreId: 'latin',
    c1: '#ff2d55',
    c2: '#8e001c',
    img: 'assets/moods/latin.jpg',
  },
  {
    label: 'Reggae / Dancehall',
    genreId: 'reggae_dancehall',
    c1: '#16a34a',
    c2: '#14532d',
    img: 'assets/moods/reggae.jpg',
  },
  {
    label: 'Blues',
    genreId: 'blues',
    c1: '#1d4ed8',
    c2: '#1e3a5f',
    img: 'assets/moods/blues.jpg',
  },
  {
    label: 'Soundtrack',
    genreId: 'film_tv',
    c1: '#7c3aed',
    c2: '#3b0764',
    img: 'assets/moods/soundtrack.jpg',
  },
  {
    label: 'Alternative',
    genreId: 'indie_alternative',
    c1: '#34c759',
    c2: '#1a7a30',
    img: 'assets/moods/indie.jpg',
  },
]

export const PLAYLIST_QUERIES = [
  'TIDAL Top Hits',
  'Pop Hits',
  'Rap Hits',
  'R&B Hits',
  'Rock Hits',
  'New Arrivals',
  'Indie Hits',
  'Country Hits',
  'DJ Hits',
  'Afrobeats Hits',
  'Latin Hits',
  'New Arrivals Hip-Hop',
  'K-Pop Hits',
  'Electronic Hits',
  'Gospel Hits',
  'Jazz Essentials',
  'New Arrivals Pop',
  'Soul Essentials',
  'Party Hits',
  'Thoro Hip-Hop',
]